---
- name: Bajar puerto de switch Cisco
  hosts: Switches
  gather_facts: no
  tasks:
    - name: Bajar puerto de la interfaz
      ios_command:
        commands: interface Gi 1/0/1
    - name: Bajar puerto de la interfaz 2
      ios_command:
        commands: shutdown
      register: result
      
    - name: Mostrar resultado
      debug:
        var: result
