---
- name: Bajar puerto de switch Cisco
  hosts: Switches
  gather_facts: no
  tasks:
    - name: Bajar puerto de la interfaz
      ios_command:
        commands:
        - configure terminal
        - interface "{{puerto}}"
        - shutdown
      register: result
      
    - name: Mostrar resultado
      debug:
        var: result
