---
- name: Bajar puerto de switch Cisco
  hosts: Switches
  gather_facts: no
  tasks:
    - name: Bajar puerto de la interfaz
      ios_command:
        commands: 
        - interface Gi 1/0/1
        - shutdown
      register: result
      
    - name: Mostrar resultado
      debug:
        var: result
