---
- name: Reinicio puerto de switch Cisco
  hosts: Switches
  gather_facts: no
  tasks:
    - name: Bajar puerto de la interfaz
      ios_command:
        commands:
        - configure terminal
        - interface {{puerto}}
        - shutdown
      register: result
      
    - name: Esperar 5 segundos
      wait_for:
        timeout: 5

    - name: Subir puerto de la interfaz
      ios_command:
        commands:
        - configure terminal
        - interface {{puerto}}
        - no shutdown   
      register: result1
      
    - name: Mostrar resultado
      debug:
        var: result
        var: result1
