---
- name: Obtener información del firewall Palo Alto
  hosts: palo_alto_firewalls
  gather_facts: no
  tasks:
    - name: Recoger hechos del firewall
      paloaltonetworks.panos.panos_facts:
        provider:
          hostname: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
      register: firewall_facts

    - name: Mostrar versión de software
      debug:
        msg: "La versión del firewall es: {{ firewall_facts.ansible_net_version }}"
