---
- name: Bajar puerto de switch Cisco
  hosts: Switches
  gather_facts: no
  tasks:
    - name: Bajar puerto de la interfaz
      ios_interface:
        name: "{{puerto}}"  
        enabled: false
      register: result
      
    - name: Mostrar resultado
      debug:
        var: result

    - name: Subir puerto de la interfaz
      ios_interface:
        name: "{{puerto}}" 
        enabled: true
      register: result
      
    - name: Mostrar resultado
      debug:
        var: result
