---
- name: Revision version switches
  hosts: switch_rojo_chaco
  gather_facts: no
  tasks:
    - name: Ejecutar comando show version
      ios_command:
        commands:
        - show version
      register: result

    - name: Mostrar resultado_bajada
      debug:
        var: result
